/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Callbacks */

#ifndef _Included_Callbacks
#define _Included_Callbacks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Callbacks
 * Method:    nativeMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Callbacks_nativeMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
