/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CubbyHole */

#ifndef _Included_CubbyHole
#define _Included_CubbyHole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CubbyHole
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CubbyHole_get
  (JNIEnv *, jobject);

/*
 * Class:     CubbyHole
 * Method:    put
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CubbyHole_put
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
