/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyTest */

#ifndef _Included_MyTest
#define _Included_MyTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyTest
 * Method:    getLine
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_MyTest_getLine
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     MyTest
 * Method:    getChar
 * Signature: (Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_MyTest_getChar
  (JNIEnv *, jobject, jobject);

/*
 * Class:     MyTest
 * Method:    getIntValue
 * Signature: ([I[D)I
 */
JNIEXPORT jint JNICALL Java_MyTest_getIntValue
  (JNIEnv *, jobject, jintArray, jdoubleArray);

/*
 * Class:     MyTest
 * Method:    createString
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_MyTest_createString
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     MyTest
 * Method:    createArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_MyTest_createArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyTest
 * Method:    getInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyTest_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     MyTest
 * Method:    handleError2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyTest_handleError2
  (JNIEnv *, jobject);

/*
 * Class:     MyTest
 * Method:    handleError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MyTest_handleError
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
