DROP TABLE USUARIOS_CENTRAIS IF EXISTS;
DROP TABLE USUARIOS IF EXISTS;
DROP TABLE COMANDOS IF EXISTS;
DROP TABLE SERVICOS_CENTRAIS_TELEFONICAS IF EXISTS;
DROP TABLE CLASSES_SERVICOS IF EXISTS;
DROP TABLE CENTRAIS_REDES IF EXISTS;
DROP TABLE VERSOES IF EXISTS;

CREATE TABLE VERSOES (
    VERS_IDENTIFICADOR_VERSAO         NUMERIC(4) NOT NULL,
    VERS_NOME                         VARCHAR(100) NOT NULL,
    VERS_DESCRICAO                    VARCHAR(160),

    PRIMARY KEY (VERS_IDENTIFICADOR_VERSAO)
);

CREATE TABLE CENTRAIS_REDES (
    CRED_NUMERO_DDD                   NUMERIC(4) NOT NULL,
    CRED_NUMERO_CENTRAL               VARCHAR(4) NOT NULL,
    CRED_TECNOLOGIA                   VARCHAR(20),
    CRED_VERS_IDENTIFICADOR_VERSAO    NUMERIC(4) NOT NULL,
    CRED_NOME                         VARCHAR(20),
    CRED_UF                           VARCHAR(4),

    PRIMARY KEY (CRED_NUMERO_DDD, CRED_NUMERO_CENTRAL),

    FOREIGN KEY (CRED_VERS_IDENTIFICADOR_VERSAO) 
        REFERENCES VERSOES (VERS_IDENTIFICADOR_VERSAO)
);

CREATE TABLE CLASSES_SERVICOS (
    CSER_CODIGO                       NUMERIC(4) NOT NULL,
    CSER_NOME                         VARCHAR(100) NOT NULL,
    PRIMARY KEY (CSER_CODIGO)
);

CREATE TABLE SERVICOS_CENTRAIS_TELEFONICAS (
    SCTE_CODIGO_SERVICO               NUMERIC(4) NOT NULL,
    SCTE_DESCRICAO                    VARCHAR(100) NOT NULL,
    SCTE_CSER_CODIGO                  NUMERIC(4),

    PRIMARY KEY (SCTE_CODIGO_SERVICO),

    FOREIGN KEY (SCTE_CSER_CODIGO) 
        REFERENCES CLASSES_SERVICOS (CSER_CODIGO)
);

CREATE TABLE COMANDOS (
    COMA_CODIGO                       NUMERIC(10) NOT NULL,
    COMA_DESCRICAO                    VARCHAR(255) NOT NULL,
    COMA_SCTE_CODIGO_SERVICO          NUMERIC(4) NOT NULL,
    COMA_VERS_IDENTIFICADOR_VERSAO    NUMERIC(4) NOT NULL,

    PRIMARY KEY (COMA_CODIGO, COMA_SCTE_CODIGO_SERVICO, COMA_VERS_IDENTIFICADOR_VERSAO),

    FOREIGN KEY (COMA_SCTE_CODIGO_SERVICO) 
        REFERENCES SERVICOS_CENTRAIS_TELEFONICAS (SCTE_CODIGO_SERVICO),

    FOREIGN KEY (COMA_VERS_IDENTIFICADOR_VERSAO) 
        REFERENCES VERSOES (VERS_IDENTIFICADOR_VERSAO)
);

CREATE TABLE USUARIOS (
    USUA_ID                           VARCHAR(20) NOT NULL,
    USUA_NOME                         VARCHAR(60) NOT NULL,
    USUA_SENHA                        VARCHAR(64) NOT NULL,
    PRIMARY KEY (USUA_ID)
);

CREATE TABLE USUARIOS_CENTRAIS (
    USCE_USUA_ID                       VARCHAR(20) NOT NULL,
    USCE_CRED_NUMERO_DDD              NUMERIC(4) NOT NULL,
    USCE_CRED_NUMERO_CENTRAL          VARCHAR(4) NOT NULL,

    PRIMARY KEY (USCE_USUA_ID, USCE_CRED_NUMERO_DDD, USCE_CRED_NUMERO_CENTRAL),

    FOREIGN KEY (USCE_USUA_ID) 
        REFERENCES USUARIOS (USUA_ID),

    FOREIGN KEY (USCE_CRED_NUMERO_DDD, USCE_CRED_NUMERO_CENTRAL) 
        REFERENCES CENTRAIS_REDES (CRED_NUMERO_DDD, CRED_NUMERO_CENTRAL)
);

INSERT INTO VERSOES (VERS_IDENTIFICADOR_VERSAO, VERS_NOME, VERS_DESCRICAO) VALUES 
    (1, 'Versao1', 'Desc. Versao1');
INSERT INTO CENTRAIS_REDES (CRED_NUMERO_DDD, CRED_NUMERO_CENTRAL, CRED_TECNOLOGIA, CRED_VERS_IDENTIFICADOR_VERSAO, CRED_NOME, CRED_UF) VALUES 
    (61, '397', 'AXE', 1, 'C397', 'DF');
INSERT INTO CENTRAIS_REDES (CRED_NUMERO_DDD, CRED_NUMERO_CENTRAL, CRED_TECNOLOGIA, CRED_VERS_IDENTIFICADOR_VERSAO, CRED_NOME, CRED_UF) VALUES 
    (61, '597', 'AXE', 1, 'C597', 'DF');
INSERT INTO CLASSES_SERVICOS (CSER_CODIGO, CSER_NOME) VALUES
    (1, 'Classe1');
INSERT INTO CLASSES_SERVICOS (CSER_CODIGO, CSER_NOME) VALUES
    (2, 'Classe2');
INSERT INTO SERVICOS_CENTRAIS_TELEFONICAS (SCTE_CODIGO_SERVICO, SCTE_DESCRICAO, SCTE_CSER_CODIGO) VALUES
    (1, 'Servico1.1', 1);
INSERT INTO SERVICOS_CENTRAIS_TELEFONICAS (SCTE_CODIGO_SERVICO, SCTE_DESCRICAO, SCTE_CSER_CODIGO) VALUES
    (2, 'Servico1.2', 1);
INSERT INTO SERVICOS_CENTRAIS_TELEFONICAS (SCTE_CODIGO_SERVICO, SCTE_DESCRICAO, SCTE_CSER_CODIGO) VALUES
    (3, 'Servico2.1', 2);
INSERT INTO COMANDOS (COMA_CODIGO, COMA_DESCRICAO, COMA_SCTE_CODIGO_SERVICO, COMA_VERS_IDENTIFICADOR_VERSAO) VALUES
    (1, 'Comando1.1.1', 1, 1);
INSERT INTO COMANDOS (COMA_CODIGO, COMA_DESCRICAO, COMA_SCTE_CODIGO_SERVICO, COMA_VERS_IDENTIFICADOR_VERSAO) VALUES
    (2, 'Comando1.1.2', 1, 1);
INSERT INTO USUARIOS (USUA_ID, USUA_NOME, USUA_SENHA) VALUES
    ('usu1', 'Usuario1', 'xxxx');
INSERT INTO USUARIOS (USUA_ID, USUA_NOME, USUA_SENHA) VALUES
    ('usu2', 'Usuario2', 'yyyy');
INSERT INTO USUARIOS_CENTRAIS (USCE_USUA_ID, USCE_CRED_NUMERO_DDD, USCE_CRED_NUMERO_CENTRAL) VALUES
    ('usu1', 61, '397');
INSERT INTO USUARIOS_CENTRAIS (USCE_USUA_ID, USCE_CRED_NUMERO_DDD, USCE_CRED_NUMERO_CENTRAL) VALUES
    ('usu1', 61, '597');
