#!/bin/sh
# Lists available cabins for a specific Cruise having a desired number of beds
# Uses command-line parameters:   
# ListCabins <cruiseID> <bedCount>
#
ant run.client_122c -Dparam.cruise=$1 -Dparam.bedcount=$2
