/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Prompt2 */

#ifndef _Included_Prompt2
#define _Included_Prompt2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Prompt2
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Prompt2_getLine__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Prompt2
 * Method:    getLine
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Prompt2_getLine__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
