<?php
$ano=date("Y");
$mes=date("M");
$semana=date("w");
$dia=date("d");
$hora=date("H");
$minuto=date("i");
$dia_semana[0]="Domingo";
$dia_semana[1]="Segunda-Feira";
$dia_semana[2]="Terça-Feira";
$dia_semana[3]="Quarta-Feira";
$dia_semana[4]="Quinta-Feira";
$dia_semana[5]="Sexta-Feira";
$dia_semana[6]="Sábado";
$mes_ano[Jan]="Janeiro";
$mes_ano[Feb]="Fevereiro";
$mes_ano[Mar]="Março";
$mes_ano[Apr]="Abril";
$mes_ano[May]="Maio";
$mes_ano[Jun]="Junho";
$mes_ano[Jul]="Julho";
$mes_ano[Aug]="Agosto";
$mes_ano[Sep]="Setembro";
$mes_ano[Oct]="Outubro";
$mes_ano[Nov]="Novembro";
$mes_ano[Dec]="Dezembro";
echo "$dia_semana[$semana], $dia de $mes_ano[$mes] de $ano - $hora:$minuto";
?>